<?php/*
Template Name: Sports Gymnastics day3
*/ ?>
<?php get_header(); ?>
<link rel="stylesheet" type="text/css" href="/css/sports-gymnastics.css">
<link href="//fonts.googleapis.com/css?family=Raleway:100" rel="stylesheet" type="text/css">
<link href="//fonts.googleapis.com/css?family=Droid+Serif" rel="stylesheet" type="text/css">
<link href="//fonts.googleapis.com/css?family=Droid+Sans" rel="stylesheet" type="text/css">
<!--css -->
<article id="sp-gym">
<h1>Gymnastics:<br> The Competitive Demands</h1>
    <p style="text-align:center;">With the Winter Olympics in full swing, the Daily Bruin takes a look at the experiences of four former Summer Olympians and current members of the UCLA gymnastics team.</p>
  <div class="pagination pagination-centered">
  <ul>
    <li><a href="http://dailybruin.com/features/gymnastics-the-competitive-demands-samantha-peszek/">Samantha Peszek</a></li>
    <li><a href="http://dailybruin.com/features/gymnastics-the-competitive-demands-jennifer-pinches/">Jennifer Pinches</a></li>
    <li class="active"><a>Jordyn Wieber</a></li>

    <li class="disabled"><a>Danusia Francis</a></li>
  </ul>
</div>

	<img src="http://dailybruin.com/images/2014/02/web.wieber.picnewA.jpg" class="aligncenter">
	<span class="photocred">Erin Ng/Daily Bruin senior staff</span><br><p style="text-align:center;">Two years after competing in the Olympics, Jordyn Wieber is serving as one of UCLA gymnastics' team managers. UCLA gymnastics coach Valorie Kondos Field praised Wieber's humility and team-first attitude, calling her "one of the most incredible people" she has ever met.<p>

<h2>Jordyn Wieber</h2>
	<p><strong>BY TAYLOR AQUINO</strong></p>

<p>Jordyn Wieber held her hands in the air as she waited for one of her teammates to high-five her after a routine.</p>

<p>Wieber, a first-year psychology student, did not perform the routine. She was not surrounded by the other members of the “Fierce Five.” She wasn’t even wearing a leotard.</p>

<div class="thumbnail with-caption-left"><img src="http://dailybruin.com/images/2014/02/web.wieber.picB_1.jpg" class="img-vert">By accepting a sponsorship deal, <br>Wieber ended her eligibility to compete <br>in college gymnastics. However, Wieber <br>has found a way to contribute as a team <br>manager for UCLA gymnastics.<br><span class="photocred-inline">Erin Ng/Daily Bruin senior staff</span></div>

<p>After soaring to the highest level of her sport, Wieber now performs a new role in the world of gymnastics: team manager.</p>

<p>Before making her way to Westwood, Wieber competed in front of a world audience. Her immortalizing moment occurred less than two years ago at the 2012 Summer Olympics in London.</p>

<p>Poised as a favorite for the all-around competition, Wieber’s chances of moving on vanished after she did not score high enough in the qualification round, falling behind two fellow American gymnasts who claimed spots in the event, the maximum allowed for any single country.</p>

<p>Though she was not able to participate in the all-around competition, Wieber still played an integral role inthe team competition and contributed to a first-place finish for the United States. </p>

<p>“It was the chance I finally got to redeem myself for not making all-around,” Wieber said. “I just kind of changed my mindset and I went in and I wanted to do whatever I could to earn that team gold medal because I knew it was my one shot.”</p>

<p>As a member of the "Fierce Five," Wieber did her part in bringing home an Olympic gold medal. It's the same team element of gymnastics that drew her to UCLA.</p>

<div class="pq-wrap-1 pq-style-1"><div class="pq-thumb"></div>
       <blockquote style-"pq-style-1">
           <p>"(Jordyn) called me ... (and) she said, ‘My dream has been to come to UCLA and be a part of the team. Could I still do that if I went professional?’ I said, ‘Jordyn, we would want you any way. ... You know we would figure out a place for you.'"</p>
       </blockquote><div class="pq-attribution">
            <p class="pq-author"> – Coach Valorie Kondos Field,</p>
            <cite>on her commitment to bringing<br>Jordyn Wieber to UCLA</cite>
          </div>
</div>
<br>
<p>After the intensity – what Wieber termed the "craziness" – of the Olympic Games and the attention generated by the team's gold medal, Wieber decided to come to UCLA for the opportunity to be part of another team.</p>

<p>But her decision to accept a professional sponsorship from Adidas ended her eligibility to compete in college gymnastics as a student-athlete.</p>

<p>"It was a really hard decision for me to make because I really had my heart set on college gymnastics, specifically UCLA,” Wieber said.</p>

<p>The reassurances of UCLA coach Valorie Kondos Field swayed her decision to commit to UCLA. After discussing her prospects at a professional career, Kondos Field said that they would find a way to make sure Wieber would be part of the team even if she could not compete.</p>

<p>Though she is not contributing to the team as a gymnast, Wieber is still an essential part of the team's daily routine, executing tasks important to performing gymnastics.</p>

<div class="thumbnail with-caption-left"><img src="http://dailybruin.com/images/2014/02/web.wieber.picD_.jpg" class="img-vert">After failing to qualify for the individual all-around, <br> Wieber helped Team USA to a gold medal in<br> London at the 2012 Summer Olympics.<br><span class="photocred-inline">(Courtesy of Jordyn Wieber)</span></div>

<p>When members of the Bruins' gymnastics team climb onto equipment to perform, Wieber moves mats and chalks bars and tells them their cues before routines. Instead of knocking out a bars routine herself, Wieber assists the other gymnasts through the paces.</p>

<p>It's a far cry from the internationally televised Olympic Games, but Wieber does not consider her job boring or humdrum.</p>

<p>"If they’re getting ready to do a beam routine and they need a mat moved, she’ll be the first one to run over and move it, and she does not look at it as menial at all," said Kondos Field. "If you ask her, she always says, ‘Oh my gosh, I’ll do whatever I can for my team.’ It’s her team. She’s taken ownership of this team. She’s part of it, as integral as if she were competing in the all-around.”</p>

<p>While Wieber is dedicated to fulfilling the physical duties of a team manager, she is also committed to helping the team with problems both personal and sports-related.</p>

<p>As a former Olympic gold medalist, she has expansive knowledge of how to succeed in gymnastics, but her influence extends beyond the confines of her winning combination of physical prowess and determination.</p>

<p>To the members of the UCLA gymnastics team, Wieber is an inspiration.</p>

<p>Sophomore Sophina DeJesus cited Wieber’s work ethic as a motivating factor in her own training.</p>

<div class="pq-wrap-1 pq-style-1"><div class="pq-thumb"></div>
       <blockquote style-"pq-style-1">
           <p>“(Jordyn) just has a very calm presence and it’s very, it’s very confident. … She has a lot of enthusiasm and a lot of passion for this team only being a freshman.”</p>
       </blockquote><div class="pq-attribution">
            <p class="pq-author"> – Samantha Peszek,</p>
            <cite>on some of the personal characteristics Jordyn Wieber has brought to the team</cite>
          </div>
</div>

<p>“Seeing her wake up extra early to come in and train was really inspiring,” DeJesus said. “She just kept working out no matter who was there, if she was by herself or not.”</p>

<p>Wieber’s journey from becoming a world-class athlete to becoming a rallying figure for the UCLA gymnastics teamis full of accolades and experiences most people never have, and never will, experience.</p>

<p>“She brings a strength, an integrity, a humility, a work ethic. I think strength is a real good word to use when describing Jordyn because she is unwavering in her strength in everything she does,” Kondos Field said. “She is a remarkable 18-year-old.”</p>

<p>Redshirt junior Samantha Peszek – who is about four years Wieber's senior – was her unofficial mentor at training camps in the Midwestwhen they were younger. Peszeksaid that Wieber’s experience as an Olympian offers another resource for gymnasts to use.</p>

<p>“Having the type of experiences that she’s had and the type of journey that she’s gone through in gymnastics herself (and) having that wisdom around the gym is just another brain to pick,” said Peszek, a silver medalist for the United States at the2008 Summer Olympics in Beijing.</p>

<p>Kondos Fieldsaid Wieber is the only gold medalist who has served as a team manager. She added that other Olympians who have taken up the role of team manager have not been as involved with the team as Wieber has.</p>

<div class="thumbnail with-caption-left"><img src="http://dailybruin.com/images/2014/02/web.wieber.picC_.jpg" class="img-vert">The experience Wieber's gained at the Olympics<br> has allowed her to serve as an invaluable source <br> of expertise and advice for team members.<br><span class="photocred-inline">(Courtesy of Jordyn Wieber)</span></div>

<p>"When she looks at, especially the freshmen, and she looks them in the eye and says, 'You can do this,' they believe it," Kondos Field said. "It's coming from someone that knows, someone that cares and she is as integrated with her freshman class and with her team as anyone else. So she doesn't think of herself as a team manager and we don't think of her as a team manager – she's a part of the team."</p>

<p>Wieber spends her time at team training as the team's manager, but trains by herself because NCAA rules prevent her from working out with the team.</p>

<p>As for whether or not she plans to re-enter the world of competitive gymnastics, Wieber said she is still unsure.</p>

<div class="pq-wrap-1 pq-style-1"><div class="pq-thumb"></div>
       <blockquote style-"pq-style-1">
           <p>“I really do believe she’s brought in a new dynamic. It’s way stronger and ... it’s a different vibe. I can’t really explain it, but I really like it. It’s great.”</p>
       </blockquote><div class="pq-attribution">
            <p class="pq-author"> – Sophomore Sophina DeJesus,</p>
            <cite>on the atmosphere change Jordyn Wieber has inspired</cite>
          </div>
</div>

<p>“I’m just kind of taking it one day at time,” Wieber said. “I’m doing one year of college and just kind of making the call from there, and then we’ll see.”</p>

<p>Though Wieber has been exposed to the world of elite gymnastics, she has not let her experiences influence her sense of self. Kondos Field said she has embraced the team and does not have a diva attitude that might be expected from an Olympian.</p>

<p>“She is so excited to be a part of this, it’s surprising to me. She got teary-eyed the other day talkingto me about it in the office, just about how much it means to her being a part of this team,” KondosField said. “She’s the antithesis of what you would think a person who’s won a gold medal … the ego they would have. She doesn’t have it. She is one of the most incredible people I have ever personally met.”</p>


<ul class="pager">
  <li class="previous">
    <a href="http://dailybruin.com/features/gymnastics-the-competitive-demands-jennifer-pinches/">&larr; Previous</a>
  </li>
  <li class="next disabled">
    <a>Next &rarr;</a>
  </li>
</ul>
</p>

<div id="page-credit">Page created by <a href="http://aeiny.com">Aein Hope</a> and <a href="mailto:cyang@media.ucla.edu">Christina Yang</a></div>



</article> 

<?php get_footer(); ?>
